---
- hosts: localhost
  tasks:
    - name: Create VM Snapshot
      kubernetes.core.k8s:
        apiVersion: snapshot.kubevirt.io/v1beta1
        kind: VirtualMachineSnapshot
        metadata:
          name: "{{ snapshot_name }}"
        spec:
          source:
            apiGroup: kubevirt.io
            kind: VirtualMachine
            name: "{{ vm_name }}"
