---
- hosts: localhost
  tasks:
    - name: Get a list of all VirtualMachines
      kubevirt.core.kubevirt_vm_info:
        namespace: "{{ namespace }}"
      register: vm_list
    - name: Print VMs
      debug:
        msg: "{{ vm_list }}"
